### ISSUE TITLE
Needs relatively linked posts

### ISSUE THREAD

**Issue by EtherTyper** [pietromenna/jekyll-cayman-theme#1]
For example, if your jekyll installation is distributed at http://debium.github.io/jekyll-cayman-theme/, the code here:

``` html
<a href="{{ site.baseurl }}{{ post.url }}">
```

interprets the post URL for "Welcome to Jekyll!" as http://debium.github.io/main/2016/02/12/sample-content.html where it should be http://debium.github.io/jekyll-cayman-theme/main/2016/02/12/sample-content.html. Thanks for listening!

**Comment by pietromenna** [comment]
@EtherTyper Thanks for reporting the issue!

**Comment by pietromenna** [comment]
Now I understood the problem, I will try to create a fix by tomorrow! Thanks a lot for reporting it.

**Comment by EtherTyper** [comment]
@pietromenna You're very welcome! I can't wait to use this for my blog!
