### ISSUE TITLE
code Syntax Highlighting not working

### ISSUE THREAD

**Issue by claudiof90** [pietromenna/jekyll-cayman-theme#16]
Hi Pietro, I have forked your repository to use it with github pages. I realized that the code syntax highlighting is not working. I tried also to change some settings in the _config.yaml file but did not sort the problem out. Is it the default behaviour or is it a bug?

**Comment by pietromenna** [comment]
Hi @claudiof90 I just tested and the syntax highlighting is not working. Please, feel free to send a PR! I will be more than happy to merge it!

**Comment by pietromenna** [comment]
Hi @claudiof90 .

I fixed in my last commit (663df7433ac2a8ea2733030e50e1968b4717c01f). Thanks for reporting!
