### ISSUE TITLE
Need a sidebar to add navigation between pages

### ISSUE THREAD

**Issue by Yvand** [pietromenna/jekyll-cayman-theme#22]
Hello, I'm trying to find the simplest way to integrate a left/right sidebar to add vertical navigation (links between pages).
But I'm very bad with HTML/CSS design so I've not been successful so far.
Is it something you could integrate?

**Comment by pietromenna** [comment]
Hi @Yvand ,

The idea of this Theme is to be as close as possible with the original one developed by GitHub pages. It does not include the side bar you are mentioning.

Thanks for your understanding, but it is not a issue of this theme.
