### ISSUE TITLE
[accessibility] Allow `lang` attribute hardcored on `<html lang="en-us">` to be optionally overwritten

### ISSUE THREAD

**Issue by fititnt** [pietromenna/jekyll-cayman-theme#25]
On https://github.com/pietromenna/jekyll-cayman-theme/blob/master/_layouts/default.html#L2 `lang="en-us"` is hardcored.

One problem with this is that pages accessed by screen readers will be spoken in a complicated accent, and understanding by a blind person may not be feasible.

The lang attribute, in fact, is one of the major factors hindering screen reading where the solution is simple, but most end-developers do not know that. Facilitating this in configuration can help to stimulate this awareness.

## References:
- WCCAG: https://www.w3.org/TR/WCAG20-TECHS/H57.html
- Problem with screen readers https://www.paciellogroup.com/blog/2016/06/using-the-html-lang-attribute/

**Comment by pietromenna** [comment]
Hi @fititnt ,

Thanks for your comments. Please, send a Pull Request with a solution proposal. Your contribution is welcome!
