### ISSUE TITLE
cayman does not work in my github pages

### ISSUE THREAD

**Issue by mudongliang** [pietromenna/jekyll-cayman-theme#27]
I add the jekyll theme - cayman in my github page through [this commit](https://github.com/mudongliang/mudongliang.github.io/commit/a29a457a840abcbef5908d14cf31175dbe650cfd) following the [instructions](https://guides.github.com/features/pages/).
But it does not work, 
![screenshot from 2017-08-26 17-34-09](https://user-images.githubusercontent.com/6214861/29745296-d62a8784-8a84-11e7-9958-17b751b5cb8d.png)

**Comment by mudongliang** [comment]
Oh, I try a new and empty [github page](https://mintcn.github.io). It works.

**Comment by pietromenna** [comment]
Hi @mudongliang . This repository is only for the jekyll theme, and not the GitHub pages ones. I am glad you found your way out! Cheers!

**Comment by RIDE55** [comment]
just trying to deploy my apps
