### ISSUE TITLE
custom /_includes not used?

### ISSUE THREAD

**Issue by monkeywithacupcake** [pietromenna/jekyll-cayman-theme#28]
I am using this awesome theme on a github project page. I created an /_includes folder and added head.html and page-header.html. Neither of these are processed in the build on github. However, custom CSS is rendered. 

You can see the folder structure here: https://github.com/monkeywithacupcake/group-travel-app
I have added a twitter card in the head and basically choose to show no text in the page-header because I replaced the gradient with an image.
In the meantime, I used css to make the text obviously small and still there. 
Please advise on what I'm missing. Thanks!

**Comment by pietromenna** [comment]
Hi @monkeywithacupcake ,

One question: are you using the Jekyll theme or the theme following the GitHub Steps?

**Comment by monkeywithacupcake** [comment]
I did not copy the whole jekyll-cayman-theme onto my computer (or fork it) and compile locally and upload. I did select cayman on the github pages setup choice. So, I think I'm following GitHub Steps, but I didn't. I apologize wholeheartedly for my lack of answer.

I'll try downloading the jekyll_caymen_theme and then merge with my current project page and see if it works. Thanks.

**Comment by monkeywithacupcake** [comment]
ok. I downloaded the zip file, made changes to the .css, includes, and index.html. Now, it looks fantastic when served locally but does not include ANY of the css when shown via github. 

Here is the image when I show locally. 
![screen shot 2017-09-12 at 08 58 54](https://user-images.githubusercontent.com/7316730/30301931-b0787f0c-9798-11e7-9d72-e7bea961711a.png)

Here is the view from github pages.
![screen shot 2017-09-12 at 08 59 07](https://user-images.githubusercontent.com/7316730/30301930-b0774880-9798-11e7-82e0-c4b6c056f953.png)

Please advise!

**Comment by monkeywithacupcake** [comment]
Nevermind. I got it. Just needed to change a few things in the config file when switching from local to github.
