### ISSUE TITLE
README.md Setup section discrepancy

### ISSUE THREAD

**Issue by ishanSrt** [pietromenna/jekyll-cayman-theme#32]
>Some important configuration can be done in the file _config.yml. Please, check the Setup section in that file.

Apparently there is no Setup section in the file _config.yml

**Comment by pietromenna** [comment]
https://github.com/pietromenna/jekyll-cayman-theme/blob/595426b7875c78da3afa4c1810f98efd3dce8b50/_config.yml#L1
