### ISSUE TITLE
An improve idea of page-footer.html

### ISSUE THREAD

**Issue by TommyJerryMairo** [pietromenna/jekyll-cayman-theme#4]
`<footer class="site-footer">
  <span class="site-footer-owner"><a href="{{ site.url  }}">{{ site.title }}</a> is maintained by <a href="mailto:{{ site.author.email }}">{{ site.author.name }}</a>.</span>
  <span class="site-footer-credits">This page was generated by <a href="https://pages.github.com">GitHub Pages</a> using the <a href="https://github.com/pietromenna/jekyll-cayman-theme">Cayman Theme</a> by <a href="http://pietro.menna.net.br/">Pietro Menna</a>.</span>
</footer>`

I believe the page-footer.html in _include can be present in this form, which is better.

**Comment by pietromenna** [comment]
Hi @TommyJerryMairo ,

Thanks for your suggestions! Please, feel free to send a Pull Request with the suggested changes.

**Comment by TommyJerryMairo** [comment]
Okay, I will how to do that first.

Sent from my ASUS

-------- 原邮件 --------
发件人:Pietro Menna notifications@github.com
已发送:Tue, 16 Feb 2016 23:11:17 +0800
收件人:pietromenna/jekyll-cayman-theme jekyll-cayman-theme@noreply.github.com
抄送:Tommy Jerry Mairo tommy.mairo@gmail.com
主题:Re: [jekyll-cayman-theme] An improve idea of page-footer.html (#4)

**Comment by TommyJerryMairo** [comment]
Learn, I mean.

Sent from my ASUS

-------- 原邮件 --------
发件人:Pietro Menna notifications@github.com
已发送:Tue, 16 Feb 2016 23:11:17 +0800
收件人:pietromenna/jekyll-cayman-theme jekyll-cayman-theme@noreply.github.com
抄送:Tommy Jerry Mairo tommy.mairo@gmail.com
主题:Re: [jekyll-cayman-theme] An improve idea of page-footer.html (#4)
