### ISSUE TITLE
The 'redcarpet' Markdown engine, no supported by GitHub Page

### ISSUE THREAD

**Issue by VadymVolos** [pietromenna/jekyll-cayman-theme#9]
> The page build completed successfully, but returned the following warning:
> 
> You are currently using the 'redcarpet' Markdown engine, which is no longer supported by GitHub Pages and may cease working at any time. To ensure your site continues to build, remove the 'markdown' setting in your site's '_config.yml' file and confirm your site renders as expected. For more information, see https://help.github.com/articles/updating-your-markdown-processor-to-kramdown.
> 
> GitHub Pages was recently upgraded to Jekyll 3.0. It may help to confirm you're using the correct dependencies:
> https://github.com/blog/2100-github-pages-now-faster-and-simpler-with-jekyll-3-0
> 
> For information on troubleshooting Jekyll see:
> https://help.github.com/articles/troubleshooting-jekyll-builds
> If you have any questions you can contact us by replying to this email.

**Comment by pietromenna** [comment]
Hi @VadymVolos ,

Thanks for reporting this! I've made some changes and it should be fixed now.
